# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "development"
    ignore:
      - dependency-name: "ergebnis/composer-normalize"
        versions: [ ">= 2.19.0" ]
      - dependency-name: "friendsofphp/php-cs-fixer"
        versions: [ ">= 3.4.0" ]
      - dependency-name: "phpunit/phpunit"
        versions: [ ">= 9" ]
      - dependency-name: "sjbr/static-info-tables"
      - dependency-name: "symfony/routing"
      - dependency-name: "symfony/yaml"
      - dependency-name: "typo3/cms-*"
      - dependency-name: "typo3/coding-standards"
        versions: [ ">= 0.7.0" ]
    versioning-strategy: "increase"
